name: Laboratory Medicine and Pathology Residency and Fellowship Programs
markdown: redcarpet
pygments: true
redirects: yes
baseurl: /fragmentary-lesion
prose:
  siteurl: 'http://bdunnette.github.io/fragmentary-lesion/'
  media: 'images'
