name: Laboratory Medicine and Pathology Residency and Fellowship Programs
markdown: redcarpet
pygments: true
redirects: yes
baseurl: /residency-jekyll
prose:
  siteurl: 'http://umn-lmp.github.io/residency-jekyll/'
  media: 'images'
